[project]
name = "virtmanager-win"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "cython>=3.1.6",
    "pyside6>=6.10.0",
]
